import { Inter } from "next/font/google";

import type { Metadata } from "next";
import type { ReactNode } from "react";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import "./globals.css";
import { CartProvider } from "@/providers/CartContext";
import { cookies } from "next/headers";
import getCart from "@/utils/Shopify/Cart/getCart";
import Overlay from "../components/overlay/overlay";
import { ModalProvider } from "@/providers/ModalContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Shopify + Next.js 14!",
};

type RootLayoutProps = {
  children: ReactNode;
};

const RootLayout = ({ children }: RootLayoutProps) => {
  const cartId = cookies().get("cartId")?.value;
  // Don't await the fetch, pass the Promise to the context provider
  const cart = getCart(cartId);

  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col min-h-screen`}>
        <ModalProvider>
          <CartProvider cartPromise={cart}>
            <Overlay />
            <Navbar />
            {children}
            <Footer />
          </CartProvider>
        </ModalProvider>
      </body>
    </html>
  );
};

export default RootLayout;
